[[redirects]]
  from = "http://powerslandscapingllc.com/*"
  to = "https://powerslandscapingllc.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.powerslandscapingllc.com/*"
  to = "https://powerslandscapingllc.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.powerslandscapingllc.com/*"
  to = "https://powerslandscapingllc.com/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
